### ISSUE TITLE
how to normalize phosphorylation  expression level?

### ISSUE THREAD

**Issue by wangbing587** [PDiracDelta/CONSTANd#1]
CONSTANd is really a fantastic method！But I have confusion about phosphorylation data normalization.
In general, we need to divide the phosphorylation  level by the protein level. 
What do you think the best steps to get normalize phosphorylation  expression level?

1. normalize protein  expression level by CONSTANd
2. normalize phosphorylation  expression level by CONSTANd
3. divide the phosphorylation  level by the protein level.

**Comment by PDiracDelta** [comment]
> CONSTANd is really a fantastic method！But I have confusion about phosphorylation data normalization.
> In general, we need to divide the phosphorylation level by the protein level.
> What do you think the best steps to get normalize phosphorylation expression level?
> 
> 1. normalize protein  expression level by CONSTANd
> 2. normalize phosphorylation  expression level by CONSTANd
> 3. divide the phosphorylation  level by the protein level.

Hi, thanks for your question. Please pose it via email to the corresponding author dirk.valkenborg@uhasselt.be 
I will close this as it is not an issue with the code or method.
